version: '3'
services:
  client:
    build:
      context: .
      dockerfile: dockerfiles/client.dockerfile
      args:
        - SERVER_IP=0.0.0.0
        - TUNNEL_SECRET=password
    image: ss-client:latest
    ports:
      - "9527:9527"
      - "9528:9528"
  server:
    build:
      context: .
      dockerfile: dockerfiles/server.dockerfile
      args:
        - NODE_BASE=node:8-alpine
    image: hualala/fe-server:latest
    ports:
      - "8000:8000"
    command: npm start
