version: '3'
services:
  client:
    build:
      context: .
      dockerfile: dockerfiles/client.dockerfile
      args:
        - SERVER_IP=0.0.0.0
        - TUNNEL_SECRET=password
    image: ss-client:latest
    ports:
      - "9527:9527"
      - "9528:9528"
